name: configure aws creds
on:
    workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: configure the credentials
              uses: aws-actions/configure-aws-credentials@v4.2.1
              with:
                role-to-assume: arn:aws:iam::884348119369:role/config-credentials-Role-cP7mzONEw8Q1
                aws-region: us-west-2
