name: configure aws creds
on:
    workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: configure the credentials
              uses: aws-actions/configure-aws-credentials
              with:
                role-to-assume: arn:aws:iam::884348119369:role/github-config-aws-creds-Role-qySS6cCdzUMu
                aws-region: us-west-2
